### ISSUE TITLE
calculate with hashbits over 64

### ISSUE THREAD

**Issue by jujudellago** [bookmate/simhash#4]
Hello,

I'm trying to figure out how to obtain more precise simhashes, using  a value higher than 64 as hashbit option. From my first tests, I could efficiently find exactly similar files, but files with very minor changes (for example 3 words changed, one added, 2 removed ) was still giving the same simhash

So I assume I should be using longer and more precise simhashes to find those small text changes, unfortunately, I can only see differences in the simhash produced for hashbit values under or equal to 64. 

In my example, the variable "mytext" is a 20'000 characters text extracted from a text file

 :009 > mytext.simhash(:split_by => / /,:hashbits =>8)
 => 189
 :010 > mytext.simhash(:split_by => / /,:hashbits =>16)
 => 4285
 :011 > mytext.simhash(:split_by => / /,:hashbits =>32)
 => 2819559613
 :012 > mytext.simhash(:split_by => / /,:hashbits =>64)
 => 10203552329699517
 :013 > mytext.simhash(:split_by => / /,:hashbits =>128)
 => 10203552329699517
:014 > mytext.simhash(:split_by => / /,:hashbits =>512)
 => 10203552329699517

I have also tried to install the gmp library to get better results, but without effect, I always get the ruby function returned
 :017 > Simhash::DEFAULT_STRING_HASH_METHOD
 => :hash_vl_rb

But if I get it right, using gmp should only improve performances, and I should get the same results from the ruby function ?

thanks

julien

**Comment by alsor** [comment]
Hello, 

I'm currently investigating similar issue. I think the problem is with the `hash_vl_rb` function which is truncating the calculated number (using `& mask`).

I'm getting better results using MD5 hash function instead, but, it's 128 bit and you cannot control its length. So resulting simhashes will also be 128 bit long.

You can try it out by yourself. First, extend String class:

```
class String
  def md5_hash(_)
    result = 0
    Digest::MD5.digest(self).bytes.each do |b|
      result <<= 8
      result += b
    end
    result
  end
end
```

then, add one extra option when calculating simhash:
`mytext.simhash(split_by: / /, hashbits: 128, hashing_method: :md5_hash)`

Would be great to hear your results.

Thanks.

**Comment by exAspArk** [comment]
Hi, 

I guess you can try using some other hash algorithms as @alsor already suggested.

Or, alternatively, you can increase offset for initial value for built-in algorithm `hash_vl_rb`, e.g.:

``` ruby
class String
  def custom_hash_vl_rb(length)
    return 0 if self == ""

    offset = length - 7
    x = bytes.first << offset
    m = 1000003
    mask = (1 << length) - 1
    each_byte { |char| x = ((x * m) ^ char.to_i) & mask }

    x ^= bytes.count
    x = -2 if x == -1
    x
  end
end

########################################################################

random_huge_string1 = `LC_CTYPE=C tr -dc A-Za-z < /dev/urandom | head -c 20000 | xargs`
random_huge_string2 = "#{string[0...10_000]}#{'a' * 1000}#{string[11_000..-1]}"

result1 = Simhash.hash(random_huge_string1.scan(/.{4}/), hashbits: 128, hashing_method: :custom_hash_vl_rb)
# => 215334935317156371507350020500929092947

result2 = Simhash.hash(random_huge_string2.scan(/.{4}/), hashbits: 128, hashing_method: :custom_hash_vl_rb)
# => 45193751856687139775807269826540259600

########################################################################

def hamming_distance(one, two)
  total = 0
  difference = one ^ two
  while difference > 0 do
    total += 1 if (difference & 1).nonzero?
    difference >>= 1
  end
  total
end

distance = hamming_distance(result1, result2)
# => 23

similarity = 1 - (distance.to_f / 128)
# => 0.8203125
```

**Comment by jujudellago** [comment]
Hi, 

Thanks a lot for your fast replies, I could successfully implement both of your solutions.

I tried both using 128 bit, and could indeed get longer simhashes, but unfortunately my sample texts with minor differences still come up as 100% similar according to the hashing.

The md5 works only with 128 bit as described, while the custom_hash_vl_rb can work with much more, but it doesn't seem relevant to go too high, the calculated simhashes were still the same with hashbit values over 10000 (and it took a really long time to process)

I will try now to push my tests a bit further to see if it can help me to find the similar files in my full documents collection.

Thanks again for your help :)

**Comment by jujudellago** [comment]
Hello,

So I could do some more experiments, the 2 described functions did give me longer simhashes, but the results were not relevant, I could find the similar documents, but a lot of other totally unrelated documents also came up.

After long experiments, I could finally find better and more efficient ways to calculate the hash, here is my function in the string methods, using SHA2:

```
   def sha2_hash(_)
     result = Digest::SHA2.hexdigest(self)
     Integer("0x#{result}").to_s         
   end

```

I did not use the same logic (I actually didn't understand what was going on in your examples), to calculate a hex, converted to integer, as I'm using the default, the calculated hash is 256 bits long.

I need to test this with much more data to be sure it is working, but on my ~700 testing collection I can find the similar documents.

Note also that I cleaned up the input text, by removing any non alphanumeric characters, putting everything to lowercase, removed the accents and any words shorter than 3 caracters, here is my cleanup function:

```
 def prepare_for_simhash(text)
    text=convert_to_utf8 text   
    unless text.nil?       
      text=I18n.transliterate(text).downcase
      text.gsub!(/[^a-z]/," ")
      text.split(/\s+/).reject{ |w| w.length<3 }.uniq.join(" ")
    else
      ""
    end
  end



 def convert_to_utf8(dump)
    enc = CharlockHolmes::EncodingDetector.detect(dump)
    if enc[:encoding]  && enc[:encoding] != 'UTF-8'
      # puts "Converting `#{enc[:encoding]}` to `UTF-8`"
      converted = CharlockHolmes::Converter.convert dump, enc[:encoding], 'UTF-8'
    else
      converted=dump
    end
    converted
  end
```

I also modified the tokenization, using this regexp:

```
:split_by => /\s+/
```
