### ISSUE TITLE
Any tips on calculate distance between simhashes?

### ISSUE THREAD

**Issue by inspire22** [bookmate/simhash#5]
I'm working on a plagiarism detector for local content, with about 12M documents.  This seems ideal, but any tips how to calculate distance between the simhashes to find a list of likely matching documents?

**Comment by jbmeerkat** [comment]
I believe part ["3.4 Locality-Sensitive Hashing for Documents"](http://infolab.stanford.edu/~ullman/mmds/ch3n.pdf) from ["Mining of Massive Datasets"](http://www.mmds.org/) can help you. It's exactly about the situation when you have a lot of documents and it's too expensive to calculate similarity iteration over each pair of documents.
